Login walkthrough
tjyoung99/step pull request #5
Opened 2020-07-02 21:36 UTC by tjyoung99

Added the library walk-through's User Authentication feature in order to manage user access to comments page.

2020-07-06 14:25 UTC, tjyoung99 commented
https://travisjy-step-2020-v2.ue.r.appspot.com/

2020-07-06 15:03 UTC, kellyktan requested changes

2020-07-06 15:03 UTC, kellyktan commented on portfolio/src/main/java/com/google/sps/servlets/LoginServlet.java
> +    }
Logout doesn't seem to work quite right on the deployed server? For me it opens a new window with my Google accounts and also doesn't log me out on your site

2020-07-06 15:18 UTC, suparnabarua requested changes

2020-07-06 15:18 UTC, suparnabarua commented on portfolio/src/main/java/com/google/sps/servlets/NicknameServlet.java
> +    String nickname = (String) entity.getProperty("nickname");
return directly

2020-07-06 15:18 UTC, suparnabarua commented on portfolio/src/main/java/com/google/sps/servlets/LoginServlet.java
> +    DatastoreService datastore = DatastoreServiceFactory.getDatastoreService();
Consider making this a shared function

2020-07-07 14:25 UTC, tjyoung99 commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +        Query.FilterOperator.EQUAL, id));
so it should look like this?:
Query query = new Query("UserInfo")
        .setFilter(FilterPredicate("id", FilterOperator.EQUAL, id));

and the imports should look like this?:
import com.google.appengine.api.datastore.Query.FilterOperator;
import com.google.appengine.api.datastore.Query.FilterPredicate;

2020-07-07 14:30 UTC, kellyktan commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +        Query.FilterOperator.EQUAL, id));
Imports: correct.
Code: take a look at my suggested change (you're missing the `new` in front of `FilterPredicate`)

2020-07-07 17:00 UTC, tjyoung99 commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +        Query.FilterOperator.EQUAL, id));
wow I just now realized that I've been looking at the suggested changes thinking that it was my code this whole time.

2020-07-07 19:27 UTC, kellyktan requested changes

2020-07-07 19:27 UTC, kellyktan commented on portfolio/src/main/java/com/google/sps/Util/GetNickname.java
> + public class GetNickname {
nit: Rename to something like NicknameUtil

2020-07-07 19:27 UTC, kellyktan commented on portfolio/src/main/java/com/google/sps/Util/GetNickname.java
> +}
newline at end of file

2020-07-07 19:27 UTC, kellyktan commented on portfolio/src/main/java/com/google/sps/Util/GetNickname.java
> + public class GetNickname {
And package/directory name should be lowercased

2020-07-07 19:27 UTC, kellyktan commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    GetNickname getNickname = new GetNickname();
For static methods, no need to create class object.  Can just call `GetNickname.getUserNickname()`

2020-07-08 13:57 UTC, suparnabarua requested changes

2020-07-08 13:57 UTC, suparnabarua commented on portfolio/src/main/java/com/google/sps/Util/GetNickname.java
> + /*** Returns the nickname of the user with id, or empty String if the user has not set a nickname.
nit. Remove the third asterisk

2020-07-08 13:57 UTC, suparnabarua commented on portfolio/src/main/java/com/google/sps/Util/GetNickname.java
> +    String nickname = (String) entity.getProperty("nickname");
You can just return, without assigning it to the nickname varfiable

2020-07-10 13:47 UTC, kellyktan requested changes

2020-07-10 13:47 UTC, kellyktan commented on portfolio/src/main/java/com/google/sps/Util/GetNickname.java
> - public class GetNickname {
Wait why did you delete this? /did you mean to rename it? Not seeing the logic anywhere else (plus the imports in other classes still reference it)

2020-07-10 20:07 UTC, tjyoung99 commented on portfolio/src/main/java/com/google/sps/Util/GetNickname.java
> - public class GetNickname {
I've been using commit -am and when I renamed getNickname the file became an untracked file so when I pushed it was excluded. I'll fix and I'll also be changing the name for those references.

2020-07-10 20:35 UTC, kellyktan approved these changes
LGTM pending final comments

2020-07-10 20:35 UTC, kellyktan commented on portfolio/src/main/java/com/google/sps/util/NicknameUtil.java
> +    */
nit: spacing

```suggestion
  /**
   * Returns the nickname of the user with id, or empty String if the user has 
   * not set a nickname.
   */
```

2020-07-10 20:35 UTC, kellyktan commented on portfolio/src/main/java/com/google/sps/util/NicknameUtil.java
> +
nit: there's an extra line here.  Also add class javadoc: 
https://docs.google.com/document/d/17zPdB6a-rw5ZBvm-XvZcxv9AyzMYsSHy0B3U1pVA0s8/edit#heading=h.7jt58ds3f8xc

2020-07-14 14:09 UTC, kellyktan approved these changes
LGTM pending my last suggestions.

2020-07-14 14:09 UTC, kellyktan commented on portfolio/src/main/java/com/google/sps/util/NicknameUtil.java
> +  /** Static utilities for checking user nicknames. */
```suggestion
/** Static utilities for checking user nicknames. */
```

2020-07-14 14:09 UTC, kellyktan commented on portfolio/src/main/java/com/google/sps/util/NicknameUtil.java
> +  */
nit: `/**` should left align with the method indentation.
```suggestion
  /** 
   * Returns the nickname of the user with id, or empty String if the user has 
   * not set a nickname.
   */
```

2020-07-15 18:13 UTC, suparnabarua approved these changes

2020-07-20 15:03 UTC, merged